
"smart_sources:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md": {"path":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md","last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"fpnzjn"}}},"last_read":{"hash":"fpnzjn","at":1760904961830},"class_name":"SmartSource","last_import":{"mtime":1751575057010,"size":17671,"at":1760904945786,"hash":"fpnzjn"},"blocks":{"#":[1,1],"#Уроки_Python":[2,2],"#Исключения в языках программирования":[3,12],"#Исключения в языках программирования#{1}":[5,12],"#Ошибки и исключения в Python":[13,48],"#Ошибки и исключения в Python#{1}":[15,16],"#Ошибки и исключения в Python#Синтаксические ошибки в Python":[17,30],"#Ошибки и исключения в Python#Синтаксические ошибки в Python#{1}":[19,30],"#Ошибки и исключения в Python#Исключения в Python":[31,48],"#Ошибки и исключения в Python#Исключения в Python#{1}":[33,48],"#Иерархия исключений в Python":[49,120],"#Иерархия исключений в Python#{1}":[51,120],"#Обработка исключений в Python":[121,220],"#Обработка исключений в Python#{1}":[123,166],"#Обработка исключений в Python#{2}":[167,167],"#Обработка исключений в Python#{3}":[168,168],"#Обработка исключений в Python#{4}":[169,169],"#Обработка исключений в Python#{5}":[170,171],"#Обработка исключений в Python#{6}":[172,220],"#Использование finally в обработке исключений":[221,251],"#Использование finally в обработке исключений#{1}":[223,251],"#Генерация исключений в Python":[252,266],"#Генерация исключений в Python#{1}":[254,266],"#Пользовательские исключения (User-defined Exceptions) в Python":[267,288],"#Пользовательские исключения (User-defined Exceptions) в Python#{1}":[269,288]},"outlinks":[{"title":"здесь","target":"https://docs.python.org/3/library/exceptions.html#bltin-exceptions","line":120},{"title":"следующим образом","target":"https://docs.python.org/3/tutorial/errors.html","line":165}],"metadata":{"tags":["#Уроки_Python"]},"task_lines":[]},"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1277tja"}}},"text":null,"length":0,"last_read":{"hash":"1277tja","at":1760904961820},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#","lines":[1,1],"size":205,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"yy3qe1"}}},"text":null,"length":0,"last_read":{"hash":"yy3qe1","at":1760904961820},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования","lines":[3,12],"size":2017,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1hft35"}}},"text":null,"length":0,"last_read":{"hash":"1hft35","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования#{1}","lines":[5,12],"size":1977,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1vg5ngs"}}},"text":null,"length":0,"last_read":{"hash":"1vg5ngs","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python","lines":[13,48],"size":1444,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"7nozw9"}}},"text":null,"length":0,"last_read":{"hash":"7nozw9","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python","lines":[17,30],"size":449,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1t5noff"}}},"text":null,"length":0,"last_read":{"hash":"1t5noff","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python#{1}","lines":[19,30],"size":414,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1awu7bi"}}},"text":null,"length":0,"last_read":{"hash":"1awu7bi","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python","lines":[31,48],"size":878,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1364xg0"}}},"text":null,"length":0,"last_read":{"hash":"1364xg0","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python#{1}","lines":[33,48],"size":854,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"uw3nmg"}}},"text":null,"length":0,"last_read":{"hash":"uw3nmg","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python","lines":[49,120],"size":2277,"outlinks":[{"title":"здесь","target":"https://docs.python.org/3/library/exceptions.html#bltin-exceptions","line":72}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1q7bdhl"}}},"text":null,"length":0,"last_read":{"hash":"1q7bdhl","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python#{1}","lines":[51,120],"size":2245,"outlinks":[{"title":"здесь","target":"https://docs.python.org/3/library/exceptions.html#bltin-exceptions","line":70}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"jyiyhz"}}},"text":null,"length":0,"last_read":{"hash":"jyiyhz","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python","lines":[121,220],"size":3723,"outlinks":[{"title":"следующим образом","target":"https://docs.python.org/3/tutorial/errors.html","line":45}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1erm9ro"}}},"text":null,"length":0,"last_read":{"hash":"1erm9ro","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{1}","lines":[123,166],"size":1571,"outlinks":[{"title":"следующим образом","target":"https://docs.python.org/3/tutorial/errors.html","line":43}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{4}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"14j8jp9"}}},"text":null,"length":0,"last_read":{"hash":"14j8jp9","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{4}","lines":[169,169],"size":309,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{5}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"augccn"}}},"text":null,"length":0,"last_read":{"hash":"augccn","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{5}","lines":[170,171],"size":265,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{6}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"61iusu"}}},"text":null,"length":0,"last_read":{"hash":"61iusu","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{6}","lines":[172,220],"size":1328,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1u7v01i"}}},"text":null,"length":0,"last_read":{"hash":"1u7v01i","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений","lines":[221,251],"size":784,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1ac18vj"}}},"text":null,"length":0,"last_read":{"hash":"1ac18vj","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений#{1}","lines":[223,251],"size":736,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"1s9mkgx"}}},"text":null,"length":0,"last_read":{"hash":"1s9mkgx","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python","lines":[252,266],"size":359,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"o7zw9h"}}},"text":null,"length":0,"last_read":{"hash":"o7zw9h","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python#{1}","lines":[254,266],"size":326,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"d1165r"}}},"text":null,"length":0,"last_read":{"hash":"d1165r","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python","lines":[267,288],"size":639,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"undefined":{"last_embed":{"hash":"lc4ozt"}}},"text":null,"length":0,"last_read":{"hash":"lc4ozt","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python#{1}","lines":[269,288],"size":573,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1277tja","at":1760904961820},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#","lines":[1,1],"size":205,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"yy3qe1","at":1760904961820},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования","lines":[3,12],"size":2017,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1hft35","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Исключения в языках программирования#{1}","lines":[5,12],"size":1977,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1vg5ngs","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python","lines":[13,48],"size":1444,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"7nozw9","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python","lines":[17,30],"size":449,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1t5noff","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Синтаксические ошибки в Python#{1}","lines":[19,30],"size":414,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1awu7bi","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python","lines":[31,48],"size":878,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1364xg0","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Ошибки и исключения в Python#Исключения в Python#{1}","lines":[33,48],"size":854,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"uw3nmg","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python","lines":[49,120],"size":2277,"outlinks":[{"title":"здесь","target":"https://docs.python.org/3/library/exceptions.html#bltin-exceptions","line":72}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1q7bdhl","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Иерархия исключений в Python#{1}","lines":[51,120],"size":2245,"outlinks":[{"title":"здесь","target":"https://docs.python.org/3/library/exceptions.html#bltin-exceptions","line":70}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"jyiyhz","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python","lines":[121,220],"size":3723,"outlinks":[{"title":"следующим образом","target":"https://docs.python.org/3/tutorial/errors.html","line":45}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1erm9ro","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{1}","lines":[123,166],"size":1571,"outlinks":[{"title":"следующим образом","target":"https://docs.python.org/3/tutorial/errors.html","line":43}],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{4}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"14j8jp9","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{4}","lines":[169,169],"size":309,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{5}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"augccn","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{5}","lines":[170,171],"size":265,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{6}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"61iusu","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Обработка исключений в Python#{6}","lines":[172,220],"size":1328,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1u7v01i","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений","lines":[221,251],"size":784,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1ac18vj","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Использование finally в обработке исключений#{1}","lines":[223,251],"size":736,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"1s9mkgx","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python","lines":[252,266],"size":359,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"o7zw9h","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Генерация исключений в Python#{1}","lines":[254,266],"size":326,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"d1165r","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python","lines":[267,288],"size":639,"outlinks":[],"class_name":"SmartBlock"},
"smart_blocks:Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python#{1}": {"path":null,"last_embed":{"hash":null},"embeddings":{"qwen3-embedding:latest":{"vec":null}},"text":null,"length":0,"last_read":{"hash":"lc4ozt","at":1760904961831},"key":"Языки программирования/Python/Учебник из сайта/Python. Урок 8. Работа с исключениями.md#Пользовательские исключения (User-defined Exceptions) в Python#{1}","lines":[269,288],"size":573,"outlinks":[],"class_name":"SmartBlock"},
